name: mes-reception

services:
  front:
    build:
      context: ./front
    container_name: mes-reception-front
    image: mes-reception-front:latest
    ports:
      - "8070:8080"
    restart: always
